name: basic-ci

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python syntax
        run: |
          python -m py_compile lambda/helper/app.py
          python -m py_compile lambda/source_check/app.py
